---
title: "Competitive Market Equilibrium With Firm Entry and Exit"
author: "Aaron Swoboda"
date: "July 3, 2017"
output: html_document
runtime: shiny
---

## Goal

Explore the effects of entry/exit on competitive market equilibrium when there are identical profit maximizing firms.

## Assumptions

* All firms are identical and are at the long run average cost minimizing production technology/scale.
* Firms are price takers. Treat price as constant.
* Firms are profit maximizing.
* Long Run equilibrium economic profits are zero.

## Firm Costs

There are two important types of costs for a firm in the long run - marginal costs and average costs. Marginal costs will help the firm find the profit maximizing level of output to produce. Average costs will help the firm make a decision regarding market entry and exit.

### Marginal Costs and Fixed Costs

For simspotifyplicity, let's give the firms a linear marginal cost curve with a given intercept and slope. Beyond the marginal cost curve, we also need to know the Fixed Costs for a firm. With just these three parameters we can calculate and graph:

* MC
* AFC
* AVC
* AC = AVC + AFC
* FC
* VC
* TC = FC + VC

## Profit Maximization

Profit maximizing firms produce the quantity such that Marginal Revenue = Marginal Cost. Because our firms are price takers, Marginal Revenue = Market Price. The firms will therefore choose to produce q such that:

$$P = MC = c + d*q.$$

This relationship between price and marginal cost is the individual firm's supply curve. 

## Market Supply Curve

If there are $n$ firms choosing to produce such that $P = MC = c*q$, then the market quantity is $Q = n*q$. Rearranging the individual supply curve to solve for q,

$$
q = (P-c)/d
$$ 

and substituting into the the equation for market quantity,

\begin{aligned}
Q &= n*q \\
& = n*(P-c)/d,
\end{aligned}

which is a relationship between the market price and the market output, in other words, the market supply curve.

## Demand

In order to find the competitive market equilibrium price and quantity, we need both the market supply and demand. Assume a linear demand curve.

$$P = a - b*Q$$

## Market Entry and Exit

We have information about the market demand and supply curves, which means we can solve for the equilibrium price and quantity. While doing so, we have thus far assumed a fixed number of firms, $n$. The current market conditions may lead to firms wishing to exit the market for better opportunities elsewhere or additional firms wanting to enter into the market because it represents a better opportunity. Long run market entry/exit incentives depend on the profitability of the existing firms in the market. Positive profits will lead to increases in $n$ as more firms enter the market. Negtive profits create incentives for firms to leave the market and thereby reduce $n$. The number of firms in the market is in equilibrium when profits are zero.

Profits for a firm are calculated as 

$$Profit = Total Revenue - Total Costs$$

Total Revenue is simply market price times quanitity produced by the firm, $q$. Total Costs are the sum of variable and fixed costs. Variable costs are the sum of all variable costs of the $q$ units produced and can be calculated as the area underneath the marginal cost curve from 0 to $q$.

Profits can also be calculated as a function of market price, the quantity produced by a firm, and average costs,

$$Profit = (Price - AC)*q.$$

Give them some parameters to put in and tell me what the graph spits out - either #s or take a picture.

```{r}
library(shiny)

ui <- fluidPage(
  fluidRow(
    column(6, 
           plotOutput("market_plot"),
           column(7,
                h4("Demand Curve"),
                splitLayout(numericInput("a", "Intercept", 100, min = 0),
                            numericInput("b", "Slope", 2)),
                 checkboxInput("show_Demand", "Plot Market Demand"),
                h4("Firm Marginal Cost Curve"),
                 splitLayout(numericInput("c", "Intercept", 0),
                             numericInput("d", "Slope", .5)),
                 checkboxInput("show_MC", "Plot Marginal Cost"),
                h4("Other Costs"),
                 numericInput("FC", "Fixed Costs", 100),
                 checkboxInput("show_TC", "Plot Total Cost")
           ),
           column(5,
                  h4("# of Firms"),
                  numericInput("n", "", 1),
                  checkboxInput("show_Supply", "Plot Market Supply"),
                  h4("Equilibrium Values"),
                  checkboxInput("show_pstar", "Market Price"),
                  checkboxInput("show_Q", "Market Q"),
                  checkboxInput("show_q", "Firm q"),
                  h4("Other Values"),
                  checkboxInput("show_TR", "Plot Total Revenue"),
                  checkboxInput("show_AC", "Plot Average Cost"),
                  checkboxInput("show_profit", "Plot Profits")
                  )
  ),
  column(6, 
         plotOutput("marginal_plot"),
         plotOutput("total_plot")
         )
))

server <- function(input, output) {
  Qstar <- function(input) (input$a - input$c)/(input$d/input$n + input$b)
  invDemand <- function(Q) input$a - input$b*Q
  TC <- function(q) input$FC + q*input$c + input$d/2*q^2
  AC <- function(q) input$FC/q + input$c + input$d/2*q
  library(RColorBrewer)
  my.palette <- brewer.pal(6, "Set2")
  colDemand <- my.palette[1]
  colSupply <- my.palette[2]
  colMC <- my.palette[3]
  colAC <- my.palette[4]
  colTC <- my.palette[5]
  colTR <- my.palette[6]
  
  output$market_plot <- renderPlot({ 
    plot(1, 1, type = "n", las = 1,
         xaxs = "i", yaxs = "i",
         xlim = c(0, Qstar(input)*1.2), xlab = "Market Quantity",
         ylim = c(0, input$a), ylab = "Market Price",
         main = "Market")
    if(input$show_Demand) abline(input$a, -1*input$b, lwd = 2, col = colDemand)
    if(input$show_Supply) abline(input$c, input$d/input$n, lwd = 2, col = colSupply)
    if(input$show_pstar) abline(h = invDemand(Qstar(input)), lty = 3)
    if(input$show_Q) {
      lines(x = c(Qstar(input), Qstar(input)), y = c(0, invDemand(Qstar(input))),
            lty = 2)
      text(Qstar(input), 0, "Q*", adj = c(0, -1))
    }
    legend("topright", bty = "n", cex = 1.5,
           legend = c("Demand", "Supply"),
           text.col = c(colDemand, colSupply))
    })
  
  output$marginal_plot <- renderPlot({
    qstar = Qstar(input)/input$n
    xmax = qstar*1.2
    plot(1, 1, type = "n", las = 1,
         xaxs = "i", yaxs = "i",
         xlim = c(0, xmax), xlab = "Firm quantity",
         ylim = c(0, input$a), ylab = "Market Price",
         main = "Marginal Analysis")
    if(input$show_pstar) abline(h = invDemand(Qstar(input)), lty = 3)
    if(input$show_MC) abline(input$c, input$d, lwd = 2, col = colMC)
    if(input$show_q) {
      lines(x = c(qstar, qstar), y = c(0, invDemand(Qstar(input))), lty = 2)
      text(qstar, 0, "q*", adj = c(0, -1))
    }
    if(input$show_AC) {
      curve(AC, add = TRUE, lwd = 2, col = colAC)
      legend("topright", bty = "n", cex = 1.5,
           legend = c("Marginal Cost", "Average Cost"),
           text.col = c(colMC, colAC))
    }
    if(!input$show_AC) {
      legend("topright", bty = "n", cex = 1.5,
           legend = c("Marginal Cost"),
           text.col = c(colMC))
    }
    if(input$show_profit) {
      polygon(x = c(0, qstar, qstar, 0),
            y = c(AC(qstar), AC(qstar), invDemand(Qstar(input)), invDemand(Qstar(input))),
            col = rgb(0, 0, 1, .15),
            border = NA)
      profit = (invDemand(Qstar(input)) - AC(qstar))*qstar
      text(qstar/2, mean(c(invDemand(Qstar(input)), AC(qstar))),
         paste("Profit =", round(profit)))

    }
    })
  
  output$total_plot <- renderPlot({
    qstar = Qstar(input)/input$n
    xmax = qstar*1.2
    plot(1, 1, type = "n", las = 1,
         xaxs = "i", yaxs = "i",
         xlim = c(0, xmax), xlab = "Firm quantity",
         ylim = c(0, max(TC(xmax), invDemand(Qstar(input))*xmax)), ylab = "$",
         main = "Total Analysis")
    if(input$show_TR) abline(0, invDemand(Qstar(input)), lwd = 2, col = colTR)
    if(input$show_TC) curve(TC, from = -1, add = TRUE, lwd = 2, col = colTC)
    if(input$show_q) {
      abline(v = qstar, lty = 2)
      text(qstar, 0, "q*", adj = c(0, -1))
    }
    legend("topleft", bty = "n", cex = 1.5,
           legend = c("Total Revenue", "Total Cost"),
           text.col = c(colTR, colTC))
    if(input$show_profit) {
      profit = invDemand(Qstar(input))*qstar - TC(qstar)
      text(qstar, mean(c(invDemand(Qstar(input))*qstar, TC(qstar))),
         paste("Profit =", round(profit)), pos = 2)
      lines(x = c(qstar, qstar), y = c(invDemand(Qstar(input))*qstar, TC(qstar)),
          col = "blue", lwd = 3) 
    }
    })
}

shinyApp(ui = ui, server = server, options = list(height = 1000))
```

